export function getTestData(): string[] {
    return [
        "OYLO Y OOOYYY LLLYOOYY O YO YLOO O OLY YL OY L YY L YOO LYL YYYOOYLOL L Y O YYYLLOY O L YYYOOYLOL YOLOLOY OOOOOOOOOO YY OO AA",
        "A B C D E F G H I J K L M N O P Q R S T U V W X Y Z",
        "MELLON MORIAMELLON MORIAMORIAMORIAMELLON MELLON MELLON MORIAMORIAMELLON MELLON MORI"
    ];
}
